Output piemers.gif

Set Shell zsh
Set FontSize 16
Set TypingSpeed 300ms
Set Padding 20
Set Width 800
Set Height 600

Sleep 1s
Type "tezaurs"
Sleep 1s
Enter
Sleep 1.5s
Type "braukt"
Sleep 1.5s
Enter
Sleep 2s
Type "jjjjjjjjjjjkkkkkkkkk"
Sleep 3s
Type"m"
Sleep 1.5s
Type "tēzaurs"
Sleep 1.5s
Enter
Sleep 3s
Type "m"
Sleep 1.5s
Type"braukt uz ku"
Sleep 1.5s
Enter
Sleep 3s
Type "m"
Sleep 1.5s
Type "piens"
Sleep 1.5s
Enter
Sleep 2s
Type "jjjjjjjjjjj"
Sleep 2s
